### ISSUE TITLE
Image Ordinals not found when using ordhook+ordinals-api but they exist in Hiro explorer

### ISSUE THREAD

**Issue by dwasyluk** [hirosystems/ordinals-api#387] opened 2024-11-21 22:31 UTC
I have ordhook running with ordinals-api running as an observer on port 20456. For some reason image ordinals don't seem to be getting indexed. For example https://api.hiro.so/ordinals/v1/inscriptions?id=3b6825e0c3e7401ef46ccfbe88a37d0a76db70ad9bc0ad2842704faeccce61b3i0 shows the ordinal but my local instance of ordinals-api shows no results (`{"limit":20,"offset":0,"total":0,"results":[]}`) when visiting http://localhost:3000/ordinals/v1/inscriptions?id=3b6825e0c3e7401ef46ccfbe88a37d0a76db70ad9bc0ad2842704faeccce61b3i0. 

In my local Postgres ordinals.chain_tip shows 845758 so this inscription should be indexed. I have both ordinals and brc20 sections configured in my Ordhook.toml:

```
[ordinals]
# Configuration for indexing Ordinals
enabled = true
start_block = 0  # Block height to start indexing from
index_transactions = true  # Enable transaction-level indexing if needed
track_transfers = true  # Track transfer events of Ordinals

[brc20]
# Configuration for indexing BRC20 tokens
enabled = true
start_block = 0  # Block height to start indexing from
track_mints = true  # Track minting events for BRC20 tokens
track_transfers = true  # Track transfer events for BRC20 tokens
track_burns = true  # Track burning events for BRC20 tokens
```

Why aren't image inscriptions behing written to the database? I'm using the release version of Ordhook (v2.2.5) and the master branch of Ordinals-api. Please help.

**Comment by dwasyluk** [comment] 2024-12-04 20:15
@rafaelcr any updates here or further info I can provide to help debug? I can't understand why so many inscriptions are missing from the pg db when connecting to ordhook using the port 20456 route. Do I also need to use `--post-to` when running ordhook as a service in order for ordinals-api to get all of the inscriptions ordhook is finding?

**Comment by rafaelcr** [comment] 2024-12-04 21:20
hi @dwasyluk apologies for the wait. We're actually working on a full revamp of the index which will make this process much faster because you will no longer need to stream events from ordhook to the API; the API will be able to read directly from the ordhook DB.

Please follow this PR for progress on this work: https://github.com/hirosystems/ordhook/pull/375

**Comment by rafaelcr** [comment] 2024-12-16 16:09
Marking as duplicate of #390

**Closed as duplicate by rafaelcr** 2024-12-16 16:09 UTC
