### ISSUE TITLE
Ordinal number inconsistencies

### ISSUE THREAD

**Issue by jack-linden** [hirosystems/ordinals-api#35] opened 2023-03-24 05:14 UTC
Sharing the same ordinal number: 
* https://api.hiro.so/ordinals/v1/inscriptions?id=b838a729651c51f1400f8ea0c11fe2b922c9b886a4d1862b312e8b02740e5003i0
* https://api.hiro.so/ordinals/v1/inscriptions?id=0eaa73ec5ae789c9b4da2b687ad0888e25a6156b5460715b15ac37d8a93b3bd8i0

Missing ordinal number: 
* https://api.hiro.so/ordinals/v1/inscriptions?from_number=503573&to_number=503575

**Comment by rafaelcr** [comment] 2023-04-11 22:22
Closing as duplicate of #23

**Closed by rafaelcr** 2023-04-11 22:22 UTC
Labels: index
