### ISSUE TITLE
null address returned from inscriptions endpoint

### ISSUE THREAD

**Issue by Vanniix** [hirosystems/ordinals-api#84] opened 2023-05-28 01:38 UTC
Occasionally the inscriptions endpoint on the API returns "null" for address. I don't see any valid situation where the address is null.

So far I have found these three inscription ids giving a null address

795c8a2f254641b184ef2e484418e5ad886350cf54888c3e5f66b9124a9bf22ci0
5a13311e0b34d1a66aa128baeab392b09c3cc2178cbd6e874d43109b4530d667i0
0bd902b5313eb257c745072297f1a68a0254c2008228ea4a3df23360392dc32di0

All three of these should have an address of bc1qrupcgrg405yyc7wza8g6h7tegn8a9an0e5vmay (at the time of writing)

URL used: https://api.hiro.so/ordinals/v1/inscriptions/{id}

This also leads to a client side error on the Hiro explorer, with console error: "tz: 'null' is not a valid P2PKH/P2SH/P2WPKH/P2WSH/P2TR address"
https://ordinals.hiro.so/inscription/0bd902b5313eb257c745072297f1a68a0254c2008228ea4a3df23360392dc32di0

**Comment by rafaelcr** [comment] 2023-06-12 14:52
This is a duplicate of #80

**Closed by rafaelcr** 2023-06-12 14:52 UTC
Labels: duplicate, index
