### ISSUE TITLE
Null to address in inscription transfers 

### ISSUE THREAD

**Issue by sam-xyz** [hirosystems/ordinals-api#359] opened 2024-05-23 05:46 UTC
**Describe the bug**
In block 837883, transaction id 27c9e16de7bcd2e560d35da9ab3f35335d4ba32eccead035c18bfe7bbd8342c0 , there are 3 inscription transfers will NULL to_address values . These 3 inscription ids are:
- 8169e36629a7d00e566e8490ceb02e395b2453b27e59b031c45179937aca41e4i0
- 83749d0b4ccaa9b2a45b29a4660c729368c41dc25769732affb093da5d4d83cai0
- 875fbec158722c3285b8f1e4b8e417778481e8ae6e61eb48f65e1bc2063af8b2i0

**To Reproduce**
1. To reproduce for 8169e36629a7d00e566e8490ceb02e395b2453b27e59b031c45179937aca41e4i0 , go to https://docs.hiro.so/ordinals/inscription-transfers 
2. Search for 8169e36629a7d00e566e8490ceb02e395b2453b27e59b031c45179937aca41e4i0
3. Look at the 4th result from ascending timestamp- you'll see that the to address is null 

**Expected behavior**
Expected result is to have non null to addresses

**Screenshots**
![image](https://github.com/hirosystems/ordinals-api/assets/110511194/cc7cb781-e3e2-4133-bef2-68765010e8f7)

**Comment by rafaelcr** [comment] 2024-05-28 16:24
hi @sam-xyz this is working as intended. When the `address` value is null or an empty string it means that the inscription was spent as fee.

**Comment by smcclellan** [comment] 2024-06-10 20:23
Closing this ticket due to the above explanation. If you believe this is incorrect, please let us know.

**Closed by smcclellan** 2024-06-10 20:23 UTC
