### ISSUE TITLE
Inconsistent inscription number between ord.io and ordinals.hiro.so

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/ordinals-api#284] opened 2023-12-13 10:30 UTC
Please see this inscription:

80b5c8bff5a645168d3d5ff2d2bd759eb6a21ba5d50e325d71decc1f03437dc1i0

https://ordinals.hiro.so/inscription/80b5c8bff5a645168d3d5ff2d2bd759eb6a21ba5d50e325d71decc1f03437dc1i0
![image](https://github.com/hirosystems/ordinals-api/assets/33360391/fcfb1884-d7bf-425b-83aa-4634a701c6f4)

https://www.ord.io/47275977
![image](https://github.com/hirosystems/ordinals-api/assets/33360391/8cd1e13b-3d67-41eb-ba1b-535a4b4a33aa)

**Comment by smcclellan** [comment] 2023-12-18 23:07
Thank you for reporting this! This seems to be a duplicate of [this ticket](https://github.com/hirosystems/ordhook/issues/229). When that ticket is complete, if this ticket is still unfixed, please reopen it or create a new one.

**Closed by smcclellan** 2023-12-18 23:07 UTC
