### ISSUE TITLE
inconsistent inscription number between api.hiro.so with ordinals.com

### ISSUE THREAD

**Issue by jiayuxiaochaoren** [hirosystems/ordinals-api#295] opened 2024-01-23 10:16 UTC
Inscription ID: 55dd8822d13b307796485678ddb122a6b59187233ad57644333ea9f902cee06di0
In api.hiro.so,it's inscription number: 52935464
<img width="608" alt="image" src="https://github.com/hirosystems/ordinals-api/assets/12232001/dbf38940-56f6-4cd0-b2c5-2ea99aee1933">
But inscription number is 52935466 in ordinals.com

<img width="946" alt="image" src="https://github.com/hirosystems/ordinals-api/assets/12232001/8c6f4ab6-5941-4ce1-b797-da524aa0f012">

**Comment by rafaelcr** [comment] 2024-01-29 15:13
This is a duplicate of https://github.com/hirosystems/ordinals-api/issues/294

**Closed by rafaelcr** 2024-01-29 15:13 UTC
